package student

var Students = []Student{
	{
		Name:    "Andry",
		Address: "Jakarta",
		Job:     "Software Developer",
		Reason:  "Saya ingin belajar pemrograman Go di Hacktiv8.",
	},
	{
		Name:    "Januwar By Khaqi",
		Address: "Surabaya",
		Job:     "Network Engineer",
		Reason:  "Saya tertarik dengan kursus Golang di Hacktiv8.",
	},
	{
		Name:    "Patrick Gustavo Bravy Walujan",
		Address: "Bandung",
		Job:     "Data Scientist",
		Reason:  "Saya ingin meningkatkan keterampilan pemrograman saya dengan belajar Go di Hacktiv8.",
	},
	{
		Name:    "Yusril Ilham Kholid",
		Address: "Yogyakarta",
		Job:     "Frontend Developer",
		Reason:  "Saya ingin bergabung dalam kelas Go di Hacktiv8.",
	},
	{
		Name:    "Yasid Al Mubarok",
		Address: "Semarang",
		Job:     "Cloud Engineer",
		Reason:  "Saya ingin memahami lebih dalam tentang pemrograman Go di Hacktiv8.",
	},
	{
		Name:    "Fahrul Zaman",
		Address: "Bandung",
		Job:     "Cloud Engineer",
		Reason:  "Saya ingin menjadi pengembang Go yang handal dengan bantuan Hacktiv8.",
	},
	{
		Name:    "Sultan Maulana Akbar Djuandadesta",
		Address: "Bandar Lampung",
		Job:     "DevOps Engineer",
		Reason:  "Saya ingin mempelajari Go secara intensif di Hacktiv8.",
	},
	{
		Name:    "Novita Ekasari",
		Address: "Surakarta",
		Job:     "Database Administrator",
		Reason:  "Saya ingin sukses sebagai pengembang Go setelah belajar di Hacktiv8.",
	},
	{
		Name:    "Ilham Rusydi Abdullah",
		Address: "Pekanbaru",
		Job:     "QA Engineer",
		Reason:  "Saya ingin menguasai pemrograman Go dengan bimbingan dari Hacktiv8.",
	},
	{
		Name:    "Muhammad Rahadian Abdurrahman'Auf All-Firdausy",
		Address: "Makassar",
		Job:     "Software Engineer",
		Reason:  "Saya ingin mendalami pemrograman Go di Hacktiv8.",
	},
	{
		Name:    "Moch. Rizal Efendi",
		Address: "Denpasar",
		Job:     "Mobile App Developer",
		Reason:  "Saya tertarik untuk belajar Go di Hacktiv8.",
	},
	{
		Name:    "Akmal Alkalafi",
		Address: "Palembang",
		Job:     "AI/Machine Learning Engineer",
		Reason:  "Saya ingin menjadi pengembang Go yang kompeten setelah mengikuti kursus Hacktiv8.",
	},
	{
		Name:    "Muhamad Rizky Maulana Soleh",
		Address: "Balikpapan",
		Job:     "System Administrator",
		Reason:  "Saya ingin bergabung dalam program belajar Go di Hacktiv8.",
	},
	{
		Name:    "Willyawan Maulana",
		Address: "Tangerang",
		Job:     "Full Stack Developer",
		Reason:  "Saya ingin mendalami ilmu pemrograman Go di Hacktiv8.",
	},
	{
		Name:    "Muhamad Ibnu Al FarezI Ramadhan",
		Address: "Bekasi",
		Job:     "DevOps Engineer",
		Reason:  "Saya ingin menjadi pengembang aplikasi Go yang handal setelah belajar di Hacktiv8.",
	},
	{
		Name:    "Zhafran Panggomgomi",
		Address: "Serang",
		Job:     "UI/UX Designer",
		Reason:  "Saya ingin memulai karir sebagai pengembang Go dengan bantuan Hacktiv8.",
	},
	{
		Name:    "Ronald Nur Sunarto",
		Address: "Purwokerto",
		Job:     "Backend Developer",
		Reason:  "Saya ingin bergabung dengan komunitas Go di Hacktiv8 dan berkontribusi.",
	},
	{
		Name:    "Farhan Dwi Oktavian",
		Address: "Cirebon",
		Job:     "Cybersecurity Analyst",
		Reason:  "Saya ingin menjadi bagian dari program belajar Go di Hacktiv8.",
	},
	{
		Name:    "Mochamad Ihsan Saepulloh",
		Address: "Pontianak",
		Job:     "DevOps Engineer",
		Reason:  "Saya ingin meningkatkan keterampilan pemrograman Go melalui Hacktiv8.",
	},
	{
		Name:    "Vormes Gema Merdeka",
		Address: "Manado",
		Job:     "Web Developer",
		Reason:  "Saya ingin unggul sebagai pengembang Go dengan mengikuti kursus-kursus di Hacktiv8.",
	},
	{
		Name:    "Muhammad Rizal Pahlevi",
		Address: "Jayapura",
		Job:     "Data Analyst",
		Reason:  "Saya ingin mempelajari pemrograman Go untuk kemajuan karir saya.",
	},
	{
		Name:    "Zeni Fitri Adibatus Salamah",
		Address: "Padang",
		Job:     "Software Engineer",
		Reason:  "Saya ingin menjadi pengembang Go yang kompeten dengan bimbingan dari Hacktiv8.",
	},
	{
		Name:    "Lukman Agung Prakoso",
		Address: "Palu",
		Job:     "Frontend Developer",
		Reason:  "Saya ingin bergabung dalam komunitas Go di Hacktiv8 dan meningkatkan keterampilan saya.",
	},
	{
		Name:    "Arrayyan Alaya Azzamachzachrie",
		Address: "Banda Aceh",
		Job:     "AI/Machine Learning Engineer",
		Reason:  "Saya ingin belajar pemrograman Go untuk mengejar karir di bidang kecerdasan buatan.",
	},
	{
		Name:    "Dirham Triyadi",
		Address: "Gorontalo",
		Job:     "Software Developer",
		Reason:  "Saya ingin menjadi pengembang Go yang terampil melalui program Hacktiv8.",
	},
}
